import type { Caso, Documento, EventoTrazabilidad, AsignaturaEquivalencia } from "@/types";

function doc(
  id: string,
  tipo: Documento["tipo"],
  nombreArchivo: string,
  overrides: Partial<Documento> = {}
): Documento {
  return {
    id,
    tipo,
    nombreArchivo,
    estado: "verificado",
    subidoEn: "2026-06-02T09:15:00-04:00",
    ...overrides,
  };
}

function evento(
  id: string,
  actor: EventoTrazabilidad["actor"],
  descripcion: string,
  fecha: string,
  extra: Partial<EventoTrazabilidad> = {}
): EventoTrazabilidad {
  return { id, actor, descripcion, fecha, ...extra };
}

function equivalencia(overrides: Partial<AsignaturaEquivalencia> & Pick<AsignaturaEquivalencia, "id" | "asignaturaExternaNombre" | "asignaturaIaccCodigo" | "asignaturaIaccNombre" | "porcentajeCoincidencia" | "propuestaIA">): AsignaturaEquivalencia {
  return {
    asignaturaExternaHoras: 68,
    asignaturaIaccSemestre: "1",
    asignaturaIaccCreditos: 6,
    nivelConfianza: overrides.porcentajeCoincidencia >= 85 ? "alta" : overrides.porcentajeCoincidencia >= 70 ? "media" : "baja",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Caso protagonista 1: Camila Fuentes Aravena (postulante, vía 6)
// ---------------------------------------------------------------------------
export const casoCamila: Caso = {
  id: "caso-camila",
  numeroCaso: "IACC-2026-0231",
  estudianteId: "est-camila",
  via: "via6-convalidacion",
  esPreConvalidacion: true,
  tieneProgramasAcademicos: true,
  carreraOrigen: "Técnico en Administración",
  institucionOrigen: "Instituto Profesional Los Andes del Sur",
  carreraDestino: "Ingeniería en Administración de Empresas",
  estado: "en-revision-humana",
  nivelConfianzaGlobal: "media",
  porcentajeConfianza: 78,
  creadoEn: "2026-06-01T10:05:00-04:00",
  antiguedadDias: 3,
  responsableActual: "J. Pérez",
  responsableRol: "coordinador-academico",
  anomaliaDocumental: true,
  documentos: [
    doc("cam-doc-1", "concentracion-notas", "Concentracion_Notas_Camila_Fuentes.pdf", {
      resultadoVerificacion: {
        legible: true,
        tieneFirma: true,
        tieneTimbre: true,
        tieneCodigoValidable: true,
        esCapturaPantalla: false,
        anomalias: [],
        datosExtraidos: {
          institucion: "Instituto Profesional Los Andes del Sur",
          carrera: "Técnico en Administración",
          cantidadAsignaturas: 8,
        },
      },
    }),
    doc("cam-doc-2", "programa-asignatura", "Programa_Contabilidad_General.pdf", {
      resultadoVerificacion: {
        legible: true,
        tieneFirma: true,
        tieneTimbre: true,
        tieneCodigoValidable: false,
        esCapturaPantalla: false,
        anomalias: [],
        datosExtraidos: { asignatura: "Contabilidad General", horas: 72, semestre: "2" },
      },
    }),
    doc("cam-doc-3", "programa-asignatura", "Programa_Matematicas_Financieras.pdf", {
      estado: "rechazado-requiere-reemplazo",
      resultadoVerificacion: {
        legible: true,
        tieneFirma: true,
        tieneTimbre: false,
        tieneCodigoValidable: false,
        esCapturaPantalla: false,
        anomalias: ["No se detectó timbre de la institución de origen"],
        datosExtraidos: { asignatura: "Matemática Financiera", horas: 54, semestre: "2" },
      },
    }),
    doc("cam-doc-4", "acta-convalidacion", "Acta_Preevaluacion_Camila.pdf"),
  ],
  equivalencias: [
    equivalencia({
      id: "cam-eq-1",
      asignaturaExternaNombre: "Administración General",
      asignaturaExternaHoras: 68,
      asignaturaIaccCodigo: "ADM-1101",
      asignaturaIaccNombre: "Fundamentos de Administración",
      asignaturaIaccSemestre: "1",
      asignaturaIaccCreditos: 6,
      porcentajeCoincidencia: 91,
      propuestaIA: "reconocer",
      decisionRevisor: "aprobado",
      fragmentoExterno: "planificación estratégica; proceso administrativo; organización empresarial; toma de decisiones",
      fragmentoExternoFuente: "Programa_Administracion_General.pdf, p. 2",
      fragmentoIacc: "planificación estratégica; proceso administrativo; organización empresarial; toma de decisiones",
      fragmentoIaccFuente: "Malla IACC — ADM-1101, p. 1",
    }),
    equivalencia({
      id: "cam-eq-2",
      asignaturaExternaNombre: "Contabilidad General",
      asignaturaExternaHoras: 72,
      asignaturaIaccCodigo: "CON-1201",
      asignaturaIaccNombre: "Fundamentos de Contabilidad",
      asignaturaIaccSemestre: "1",
      asignaturaIaccCreditos: 6,
      porcentajeCoincidencia: 91,
      propuestaIA: "reconocer",
      decisionRevisor: "aprobado",
      fragmentoExterno: "contabilidad general; estados financieros; libro diario; balance general",
      fragmentoExternoFuente: "Programa_Contabilidad_General.pdf, p. 1",
      fragmentoIacc: "contabilidad general; estados financieros; libro diario; balance general; principios contables",
      fragmentoIaccFuente: "Malla IACC — CON-1201, p. 1",
    }),
    equivalencia({
      id: "cam-eq-3",
      asignaturaExternaNombre: "Gestión de Personal",
      asignaturaExternaHoras: 60,
      asignaturaIaccCodigo: "ADM-2102",
      asignaturaIaccNombre: "Gestión de Recursos Humanos",
      asignaturaIaccSemestre: "3",
      asignaturaIaccCreditos: 5,
      porcentajeCoincidencia: 88,
      propuestaIA: "reconocer",
      decisionRevisor: "aprobado",
      fragmentoExterno: "reclutamiento y selección; capacitación; evaluación de desempeño",
      fragmentoExternoFuente: "Programa_Gestion_Personal.pdf, p. 3",
      fragmentoIacc: "reclutamiento y selección; capacitación; evaluación de desempeño; clima organizacional",
      fragmentoIaccFuente: "Malla IACC — ADM-2102, p. 2",
    }),
    equivalencia({
      id: "cam-eq-4",
      asignaturaExternaNombre: "Fundamentos de Marketing",
      asignaturaExternaHoras: 60,
      asignaturaIaccCodigo: "ADM-2103",
      asignaturaIaccNombre: "Marketing Estratégico",
      asignaturaIaccSemestre: "3",
      asignaturaIaccCreditos: 5,
      porcentajeCoincidencia: 86,
      propuestaIA: "reconocer",
      decisionRevisor: "aprobado",
      fragmentoExterno: "segmentación de mercado; mix de marketing; posicionamiento",
      fragmentoExternoFuente: "Programa_Marketing.pdf, p. 2",
      fragmentoIacc: "segmentación de mercado; mix de marketing; posicionamiento; comportamiento del consumidor",
      fragmentoIaccFuente: "Malla IACC — ADM-2103, p. 1",
    }),
    equivalencia({
      id: "cam-eq-5",
      asignaturaExternaNombre: "Costos Empresariales",
      asignaturaExternaHoras: 60,
      asignaturaIaccCodigo: "ADM-2301",
      asignaturaIaccNombre: "Costos y Presupuestos",
      asignaturaIaccSemestre: "4",
      asignaturaIaccCreditos: 6,
      porcentajeCoincidencia: 85,
      propuestaIA: "reconocer",
      decisionRevisor: "aprobado",
      fragmentoExterno: "costos fijos y variables; punto de equilibrio; presupuesto operacional",
      fragmentoExternoFuente: "Programa_Costos.pdf, p. 2",
      fragmentoIacc: "costos fijos y variables; punto de equilibrio; presupuesto operacional; análisis de costos",
      fragmentoIaccFuente: "Malla IACC — ADM-2301, p. 1",
    }),
    equivalencia({
      id: "cam-eq-6",
      asignaturaExternaNombre: "Matemática Financiera",
      asignaturaExternaHoras: 54,
      asignaturaIaccCodigo: "ADM-1301",
      asignaturaIaccNombre: "Matemática Financiera",
      asignaturaIaccSemestre: "2",
      asignaturaIaccCreditos: 5,
      porcentajeCoincidencia: 82,
      propuestaIA: "reconocer",
      decisionRevisor: "aprobado",
      fragmentoExterno: "interés simple; interés compuesto; anualidades",
      fragmentoExternoFuente: "Programa_Matematicas_Financieras.pdf, p. 1",
      fragmentoIacc: "interés simple; interés compuesto; anualidades; valor presente; valor futuro",
      fragmentoIaccFuente: "Malla IACC — ADM-1301, p. 1",
    }),
    equivalencia({
      id: "cam-eq-7",
      asignaturaExternaNombre: "Logística Empresarial",
      asignaturaExternaHoras: 50,
      asignaturaIaccCodigo: "ADM-2201",
      asignaturaIaccNombre: "Gestión Logística",
      asignaturaIaccSemestre: "4",
      asignaturaIaccCreditos: 5,
      porcentajeCoincidencia: 68,
      nivelConfianza: "baja",
      propuestaIA: "revisar",
      motivoNoReconocimiento: "El contenido cubre solo distribución básica; falta profundidad en gestión de inventarios y abastecimiento.",
      fragmentoExterno: "distribución de productos; canales de venta",
      fragmentoExternoFuente: "Programa_Logistica.pdf, p. 1",
      fragmentoIacc: "cadena de suministro; gestión de inventarios; distribución; logística de abastecimiento",
      fragmentoIaccFuente: "Malla IACC — ADM-2201, p. 1",
    }),
    equivalencia({
      id: "cam-eq-8",
      asignaturaExternaNombre: "Gestión de Proyectos I",
      asignaturaExternaHoras: 40,
      asignaturaIaccCodigo: "ADM-3101",
      asignaturaIaccNombre: "Gestión de Proyectos",
      asignaturaIaccSemestre: "5",
      asignaturaIaccCreditos: 5,
      porcentajeCoincidencia: 55,
      nivelConfianza: "baja",
      propuestaIA: "revisar",
      motivoNoReconocimiento: "Programa introductorio, no cubre gestión de riesgos ni herramientas de seguimiento (carta Gantt).",
      fragmentoExterno: "planificación básica de tareas",
      fragmentoExternoFuente: "Programa_Gestion_Proyectos.pdf, p. 1",
      fragmentoIacc: "planificación de proyectos; carta gantt; gestión de riesgos; seguimiento y control",
      fragmentoIaccFuente: "Malla IACC — ADM-3101, p. 1",
    }),
  ],
  trazabilidad: [
    evento("cam-tz-1", "plataforma-ia", "Extrajo 8 asignaturas desde 3 documentos (OCR)", "2026-06-01T10:06:00-04:00"),
    evento("cam-tz-2", "plataforma-ia", "Detectó ausencia de timbre en Programa_Matematicas_Financieras.pdf", "2026-06-01T10:06:30-04:00"),
    evento("cam-tz-3", "plataforma-ia", "Calculó porcentaje de coincidencia para 8 asignaturas contra malla de Ingeniería en Administración de Empresas", "2026-06-01T10:07:00-04:00"),
    evento("cam-tz-4", "persona-iacc", "Validó documentación entregada", "2026-06-02T09:20:00-04:00", { nombreActor: "M. Torres", rolActor: "Registro Curricular" }),
    evento("cam-tz-5", "persona-iacc", "Revisó y aprobó 6 equivalencias propuestas por la plataforma", "2026-06-03T11:40:00-04:00", { nombreActor: "J. Pérez", rolActor: "Coordinador académico" }),
  ],
};

// ---------------------------------------------------------------------------
// Caso protagonista 2: Rodrigo Salas Miranda (matriculado, vía 5, doc pendiente)
// ---------------------------------------------------------------------------
export const casoRodrigo: Caso = {
  id: "caso-rodrigo",
  numeroCaso: "IACC-2025-0088",
  estudianteId: "est-rodrigo",
  via: "via5-rfcp",
  casuisticaVia5: "sin-codigo-validacion",
  carreraOrigen: "Técnico en Prevención de Riesgos",
  institucionOrigen: "CFT Valle Central",
  carreraDestino: "Ingeniería en Prevención de Riesgos",
  estado: "bloqueado-documento-pendiente",
  nivelConfianzaGlobal: "alta",
  porcentajeConfianza: 96,
  creadoEn: "2025-08-04T09:00:00-04:00",
  antiguedadDias: 373,
  responsableActual: "A. Reyes",
  responsableRol: "analista-diferenciados",
  ciclosSinDocumento: 1,
  plazoDocumentoPendiente: "2026-08-30",
  documentos: [
    doc("rod-doc-1", "certificado-titulo", "Certificado_Titulo_Rodrigo_Salas.pdf", {
      resultadoVerificacion: {
        legible: true,
        tieneFirma: true,
        tieneTimbre: true,
        tieneCodigoValidable: false,
        esCapturaPantalla: false,
        anomalias: ["No se encontró código de validación"],
        datosExtraidos: { institucion: "CFT Valle Central", carrera: "Técnico en Prevención de Riesgos" },
      },
    }),
    doc("rod-doc-2", "declaracion-jurada", "Declaracion_Jurada_Titulo_Rodrigo_Salas.pdf"),
  ],
  equivalencias: [
    equivalencia({
      id: "rod-eq-1",
      asignaturaExternaNombre: "Fundamentos de Prevención (1er y 2do año)",
      asignaturaExternaHoras: 0,
      asignaturaIaccCodigo: "PRI-1101",
      asignaturaIaccNombre: "Fundamentos de Prevención de Riesgos",
      asignaturaIaccSemestre: "1",
      asignaturaIaccCreditos: 6,
      porcentajeCoincidencia: 100,
      propuestaIA: "reconocer",
      decisionRevisor: "aprobado",
      fragmentoExterno: "Reconocimiento por título previo (RFCP): los dos primeros años quedan cubiertos por el título de Técnico en Prevención de Riesgos.",
      fragmentoIacc: "higiene ocupacional; seguridad laboral; accidentabilidad; normativa legal vigente",
    }),
  ],
  trazabilidad: [
    evento("rod-tz-1", "plataforma-ia", "Verificó certificado de título: sin código de validación", "2025-08-04T09:05:00-04:00"),
    evento("rod-tz-2", "persona-iacc", "Validó declaración jurada de título y activó plazo de entrega", "2025-08-05T10:00:00-04:00", { nombreActor: "M. Torres", rolActor: "Registro Curricular" }),
    evento("rod-tz-3", "persona-iacc", "Aprobó RFCP: reconocimiento de los dos primeros años de la carrera", "2025-08-06T15:30:00-04:00", { nombreActor: "A. Reyes", rolActor: "Analista de Ingresos Diferenciados" }),
    evento("rod-tz-4", "plataforma-ia", "Certificado de título legalizado no llegó durante el segundo ciclo: se generó bloqueo de inscripción", "2026-07-15T00:00:00-04:00"),
  ],
};

// ---------------------------------------------------------------------------
// Casos de relleno para poblar la bandeja del backoffice (11 casos)
// ---------------------------------------------------------------------------
const casosRelleno: Caso[] = [
  {
    id: "caso-003",
    numeroCaso: "IACC-2026-0103",
    estudianteId: "est-003",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: true,
    carreraOrigen: "Técnico en Informática",
    institucionOrigen: "Instituto Profesional Cordillera",
    carreraDestino: "Ingeniería en Informática",
    estado: "resuelto-reconocido",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 93,
    creadoEn: "2026-05-20T09:00:00-04:00",
    antiguedadDias: 15,
    responsableActual: "J. Pérez",
    responsableRol: "coordinador-academico",
    documentos: [doc("d-003-1", "concentracion-notas", "Concentracion_Notas_003.pdf"), doc("d-003-2", "programa-asignatura", "Programa_BD_003.pdf")],
    equivalencias: [
      equivalencia({ id: "eq-003-1", asignaturaExternaNombre: "Base de Datos I", asignaturaIaccCodigo: "INF-1201", asignaturaIaccNombre: "Base de Datos", porcentajeCoincidencia: 93, propuestaIA: "reconocer", decisionRevisor: "aprobado" }),
    ],
    trazabilidad: [evento("tz-003-1", "plataforma-ia", "Extrajo asignaturas y calculó coincidencia", "2026-05-20T09:10:00-04:00")],
  },
  {
    id: "caso-004",
    numeroCaso: "IACC-2025-0104",
    estudianteId: "est-004",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: true,
    carreraOrigen: "Técnico en Administración",
    institucionOrigen: "Instituto Profesional Los Andes del Sur",
    carreraDestino: "Ingeniería en Administración de Empresas",
    estado: "cerrado",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 91,
    creadoEn: "2025-03-10T09:00:00-04:00",
    antiguedadDias: 520,
    responsableActual: "A. Reyes",
    responsableRol: "analista-diferenciados",
    documentos: [doc("d-004-1", "programa-asignatura", "Programa_Contabilidad_004.pdf")],
    equivalencias: [
      equivalencia({ id: "eq-004-1", asignaturaExternaNombre: "Contabilidad General", asignaturaIaccCodigo: "CON-1201", asignaturaIaccNombre: "Fundamentos de Contabilidad", porcentajeCoincidencia: 91, propuestaIA: "reconocer", decisionRevisor: "aprobado" }),
    ],
    trazabilidad: [evento("tz-004-1", "persona-iacc", "Cerró caso, criterio quedó registrado en memoria de casos", "2025-03-15T10:00:00-04:00", { nombreActor: "J. Pérez", rolActor: "Coordinador académico" })],
  },
  {
    id: "caso-005",
    numeroCaso: "IACC-2026-0205",
    estudianteId: "est-005",
    via: "via5-rfcp",
    casuisticaVia5: "con-codigo-validacion",
    carreraOrigen: "Técnico en Trabajo Social",
    institucionOrigen: "CFT Río Claro",
    carreraDestino: "Trabajo Social",
    estado: "en-verificacion",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 97,
    creadoEn: "2026-08-05T09:00:00-04:00",
    antiguedadDias: 7,
    responsableActual: "M. Torres",
    responsableRol: "registro-curricular",
    documentos: [doc("d-005-1", "certificado-titulo", "Certificado_Titulo_005.pdf", { resultadoVerificacion: { legible: true, tieneFirma: true, tieneTimbre: true, tieneCodigoValidable: true, esCapturaPantalla: false, anomalias: [] } })],
    equivalencias: [],
    trazabilidad: [evento("tz-005-1", "plataforma-ia", "Validó código de validación contra registro de la institución emisora", "2026-08-05T09:05:00-04:00")],
  },
  {
    id: "caso-006",
    numeroCaso: "IACC-2026-0206",
    estudianteId: "est-006",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: false,
    carreraOrigen: "Técnico en Recursos Humanos",
    institucionOrigen: "CFT Valle Central",
    carreraDestino: "Ingeniería en Administración de Empresas",
    estado: "en-revision-humana",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 88,
    creadoEn: "2026-08-01T09:00:00-04:00",
    antiguedadDias: 11,
    responsableActual: "J. Pérez",
    responsableRol: "coordinador-academico",
    documentos: [doc("d-006-1", "concentracion-notas", "Concentracion_Notas_006.pdf")],
    equivalencias: [
      equivalencia({
        id: "eq-006-1",
        asignaturaExternaNombre: "Administración General",
        asignaturaIaccCodigo: "ADM-1101",
        asignaturaIaccNombre: "Fundamentos de Administración",
        porcentajeCoincidencia: 88,
        propuestaIA: "reconocer",
        casoPrevioReferenciaId: "caso-007",
        casoPrevioReferenciaNumero: "IACC-2025-0107",
      }),
    ],
    trazabilidad: [evento("tz-006-1", "plataforma-ia", "Consultó memoria de casos: encontró criterio previo en caso IACC-2025-0107", "2026-08-01T09:08:00-04:00")],
  },
  {
    id: "caso-007",
    numeroCaso: "IACC-2025-0107",
    estudianteId: "est-007",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: true,
    carreraOrigen: "Técnico en Administración",
    institucionOrigen: "CFT Valle Central",
    carreraDestino: "Ingeniería en Administración de Empresas",
    estado: "cerrado",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 88,
    creadoEn: "2025-02-01T09:00:00-04:00",
    antiguedadDias: 555,
    responsableActual: "J. Pérez",
    responsableRol: "coordinador-academico",
    documentos: [doc("d-007-1", "programa-asignatura", "Programa_Administracion_007.pdf")],
    equivalencias: [
      equivalencia({ id: "eq-007-1", asignaturaExternaNombre: "Administración General", asignaturaIaccCodigo: "ADM-1101", asignaturaIaccNombre: "Fundamentos de Administración", porcentajeCoincidencia: 88, propuestaIA: "reconocer", decisionRevisor: "aprobado" }),
    ],
    trazabilidad: [evento("tz-007-1", "persona-iacc", "Cerró caso, quedó registrado como precedente", "2025-02-10T10:00:00-04:00", { nombreActor: "J. Pérez", rolActor: "Coordinador académico" })],
  },
  {
    id: "caso-008",
    numeroCaso: "IACC-2026-0208",
    estudianteId: "est-008",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: true,
    esPreConvalidacion: true,
    carreraOrigen: "Ingeniería en Administración (incompleta)",
    institucionOrigen: "Instituto Profesional Costa del Pacífico",
    carreraDestino: "Ingeniería en Administración de Empresas",
    estado: "documentos-pendientes",
    nivelConfianzaGlobal: "baja",
    porcentajeConfianza: 42,
    creadoEn: "2026-08-10T09:00:00-04:00",
    antiguedadDias: 2,
    responsableActual: "M. Torres",
    responsableRol: "registro-curricular",
    anomaliaDocumental: true,
    documentos: [
      doc("d-008-1", "concentracion-notas", "captura_notas_sistema.png", {
        estado: "rechazado-requiere-reemplazo",
        resultadoVerificacion: { legible: true, tieneFirma: false, tieneTimbre: false, tieneCodigoValidable: false, esCapturaPantalla: true, anomalias: ["Es una captura de pantalla de un sistema en línea, no un documento oficial", "No se detectó firma", "No se detectó timbre de la institución de origen"] },
      }),
    ],
    equivalencias: [],
    trazabilidad: [evento("tz-008-1", "plataforma-ia", "Rechazó documento: captura de pantalla sin firma ni timbre", "2026-08-10T09:03:00-04:00")],
  },
  {
    id: "caso-009",
    numeroCaso: "IACC-2025-0109",
    estudianteId: "est-009",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: true,
    carreraOrigen: "Técnico en Prevención de Riesgos",
    institucionOrigen: "Instituto Profesional Cordillera",
    carreraDestino: "Ingeniería en Prevención de Riesgos",
    estado: "cerrado",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 90,
    creadoEn: "2025-04-12T09:00:00-04:00",
    antiguedadDias: 487,
    responsableActual: "A. Reyes",
    responsableRol: "analista-diferenciados",
    documentos: [doc("d-009-1", "programa-asignatura", "Programa_Higiene_009.pdf")],
    equivalencias: [
      equivalencia({ id: "eq-009-1", asignaturaExternaNombre: "Higiene y Seguridad Laboral", asignaturaIaccCodigo: "PRI-1101", asignaturaIaccNombre: "Fundamentos de Prevención de Riesgos", porcentajeCoincidencia: 90, propuestaIA: "reconocer", decisionRevisor: "aprobado" }),
    ],
    trazabilidad: [evento("tz-009-1", "persona-iacc", "Cerró caso, precedente para memoria de casos", "2025-04-20T10:00:00-04:00", { nombreActor: "A. Reyes", rolActor: "Analista de Ingresos Diferenciados" })],
  },
  {
    id: "caso-010",
    numeroCaso: "IACC-2026-0210",
    estudianteId: "est-010",
    via: "via5-rfcp",
    casuisticaVia5: "requiere-autorizacion-jefe-disciplinar",
    carreraOrigen: "Técnico en Administración",
    institucionOrigen: "CFT Bicentenario del Maule",
    carreraDestino: "Ingeniería en Administración de Empresas",
    estado: "en-revision-humana",
    nivelConfianzaGlobal: "media",
    porcentajeConfianza: 74,
    creadoEn: "2026-07-28T09:00:00-04:00",
    antiguedadDias: 15,
    responsableActual: "A. Reyes",
    responsableRol: "analista-diferenciados",
    autorizacionJefeDisciplinar: { motivo: "titulo-mas-10-anios", estado: "pendiente" },
    documentos: [doc("d-010-1", "certificado-titulo", "Certificado_Titulo_010.pdf")],
    equivalencias: [],
    trazabilidad: [evento("tz-010-1", "plataforma-ia", "Detectó título con más de 10 años de antigüedad: deriva a autorización de jefe disciplinar", "2026-07-28T09:05:00-04:00")],
  },
  {
    id: "caso-011",
    numeroCaso: "IACC-2026-0211",
    estudianteId: "est-011",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: true,
    carreraOrigen: "Técnico en Contabilidad General",
    institucionOrigen: "Instituto Profesional Valle Verde",
    carreraDestino: "Ingeniería en Administración de Empresas",
    estado: "en-revision-humana",
    nivelConfianzaGlobal: "baja",
    porcentajeConfianza: 62,
    creadoEn: "2026-07-10T09:00:00-04:00",
    antiguedadDias: 33,
    responsableActual: "J. Pérez",
    responsableRol: "coordinador-academico",
    documentos: [doc("d-011-1", "programa-asignatura", "Programa_Costos_011.pdf")],
    equivalencias: [
      equivalencia({ id: "eq-011-1", asignaturaExternaNombre: "Costos Básicos", asignaturaIaccCodigo: "ADM-2301", asignaturaIaccNombre: "Costos y Presupuestos", porcentajeCoincidencia: 62, nivelConfianza: "baja", propuestaIA: "revisar", motivoNoReconocimiento: "Contenido insuficiente en presupuesto operacional" }),
    ],
    trazabilidad: [evento("tz-011-1", "plataforma-ia", "Coincidencia bajo el umbral: deriva a revisión académica", "2026-07-10T09:10:00-04:00")],
  },
  {
    id: "caso-012",
    numeroCaso: "IACC-2026-0212",
    estudianteId: "est-012",
    via: "via5-rfcp",
    casuisticaVia5: "sin-codigo-validacion",
    carreraOrigen: "Técnico en Informática",
    institucionOrigen: "CFT Aconcagua",
    carreraDestino: "Ingeniería en Informática",
    estado: "eliminado-documento-pendiente",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 95,
    creadoEn: "2024-06-01T09:00:00-04:00",
    antiguedadDias: 802,
    responsableActual: "A. Reyes",
    responsableRol: "analista-diferenciados",
    ciclosSinDocumento: 2,
    documentos: [doc("d-012-1", "certificado-titulo", "Certificado_Titulo_012.pdf", { resultadoVerificacion: { legible: true, tieneFirma: true, tieneTimbre: true, tieneCodigoValidable: false, esCapturaPantalla: false, anomalias: ["No se encontró código de validación"] } })],
    equivalencias: [],
    trazabilidad: [
      evento("tz-012-1", "plataforma-ia", "Certificado sin código de validación: declaración jurada firmada", "2024-06-02T09:00:00-04:00"),
      evento("tz-012-2", "plataforma-ia", "Documento legalizado no llegó tras dos ciclos: caso eliminado por documento pendiente", "2025-06-01T00:00:00-04:00"),
    ],
  },
  {
    id: "caso-013",
    numeroCaso: "IACC-2026-0213",
    estudianteId: "est-013",
    via: "via6-convalidacion",
    tieneProgramasAcademicos: true,
    carreraOrigen: "Técnico en Trabajo Social",
    institucionOrigen: "Instituto Profesional Los Andes del Sur",
    carreraDestino: "Trabajo Social",
    estado: "resuelto-reconocido",
    nivelConfianzaGlobal: "alta",
    porcentajeConfianza: 89,
    creadoEn: "2026-06-15T09:00:00-04:00",
    antiguedadDias: 58,
    responsableActual: "J. Pérez",
    responsableRol: "coordinador-academico",
    documentos: [doc("d-013-1", "programa-asignatura", "Programa_Psicologia_013.pdf")],
    equivalencias: [
      equivalencia({ id: "eq-013-1", asignaturaExternaNombre: "Psicología de Grupos", asignaturaIaccCodigo: "TRS-1201", asignaturaIaccNombre: "Psicología Social", porcentajeCoincidencia: 89, propuestaIA: "reconocer", decisionRevisor: "aprobado" }),
    ],
    trazabilidad: [evento("tz-013-1", "persona-iacc", "Aprobó equivalencia propuesta", "2026-06-20T10:00:00-04:00", { nombreActor: "J. Pérez", rolActor: "Coordinador académico" })],
  },
];

export const casosSeed: Caso[] = [casoCamila, casoRodrigo, ...casosRelleno];
